owner: sabir-gbs
repo: upsidia-status

sites:
  - name: Upsidia Homepage
    url: https://upsidia.ai
    
  - name: Upsidia Leaderboard  
    url: https://upsidia.ai/leaderboard

status-website:
  cname: status.upsidia.ai
  name: Upsidia Status
  logoUrl: https://upsidia.ai/logo.png  # optional: add your logo URL
  introTitle: "**Upsidia.ai** Status"
  introMessage: Real-time monitoring of Upsidia's website performance tracking platform
  navbar:
    - title: Status
      href: /
    - title: Back to Upsidia
      href: https://upsidia.ai

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0,15,30,45 * * * *"  # Every 15 minutes
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"  # Every 5 minutes
